### ISSUE TITLE
evil-embrace opens new windows

### ISSUE THREAD

**Issue by Somelauw** [cute-jumper/evil-embrace.el#5] opened 2017-08-14 11:47 UTC
#### Steps to reproduce
- $ emacs -Q
- package-initialize
- (require 'evil)
- (require 'evil-surround)
- global-evil-surround-mode
- (require 'which-key)
- which-key-mode
- (require 'evil-embrace)
- evil-embrace-enable-evil-surround-integration
- Type "hello" (without the quotes)
- ys (wait a second) iw (wait a second) b

#### Expected behaviour
It leaves (hello) and no new windows are created

#### Actual Behaviour
It leaves (hello), but the window has split vertically

#### Info
Emacs 25.2.2

**Comment by cute-jumper** [comment] 2017-08-14 16:55
Hi. Thanks for reporting! To reproduce the problem, I have to wait for a second after "i". It looks like  `which-key` and `embrace` interfere with each other. I'll find some time to look into it.

**Comment by kassick** [comment] 2017-10-31 14:04
Setting `which-key-popup-type` to `'minibuffer` seems to avoid the problem described by @Somelauw. 

In my case, the issue also appears when using helm-mode:

In an org file:
ysiwl (surround inner word , embrace with BEGIN/END) -- a helm window pops up to select the block type. After selecting one of the available block types, the window used by helm persists.

With the cursor in the original window, C-x 1  *does not delete the window used by embrace-help*.

I did a kludge that fixes both these problems. It does so by storing the window used by embrace--show-help-buffer and making sure it's no longer used after embrace-{region, change, delete} . It's in https://github.com/kassick/evil-embrace.el .

I think this should actually be in embrace.el (not evil-embrace) and that the solution would actually be to use more robust window-management in embrace.el -- but my emacs-foo isn't very strong.

**Comment by kassick** [comment] 2017-10-31 15:02
Out-of-tree fix: https://bitbucket.org/snippets/kassick/BqyEdx
File must be required *before* `evil-embrace-enable-surround-integration` .

**Comment by cute-jumper** [comment] 2017-10-31 18:37
@kassick Thanks for the effort! Reminded me of this issue. I pushed a quick fix https://github.com/cute-jumper/embrace.el/commit/dd5da196e5bcc5e6d87e1937eca0c21da4334ef2. Let me know if this commit fixes the problem or not. Thanks! cc @Somelauw

**Comment by kassick** [comment] 2017-10-31 21:09
@cute-jumper Yup, it fixes for me (which-key and helm issues), thanks!

**Comment by cute-jumper** [comment] 2017-11-01 01:29
Awesome. I'll close this and if any problem pops out, feel free to reopen this issue.

**Closed as completed by cute-jumper** 2017-11-01 01:29 UTC
